---
version: "3.9"
services:
  foodvariety:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - "db"
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "random"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: foodvariety
      MYSQL_USER: foodvariety
      MYSQL_PASSWORD: foodvariety
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: