spring:
  datasource:
    url: jdbc:mysql://db:3306/foodvariety
    username: foodvariety
    password: foodvariety
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foodvariety
    username: foodvariety
    password: foodvariety